"""Provider-neutral fiscal gateway surface."""

from .authorization import (
    AuthorizationRequest,
    AuthorizationResult,
    AuthorizationStatus,
    FiscalGateway,
    FiscalGatewayClient,
    GatewayContractError,
    GatewayProviderMetadata,
)
from .fake import FakeFiscalGateway, FakeGatewayMode
from .provider import (
    ConfiguredProviderAdapter,
    CscUnavailableError,
    FiscalProviderTransport,
    MalformedProviderResponseError,
    ProviderAuthenticationError,
    ProviderCredentialsUnavailableError,
    ProviderDescriptor,
    ProviderGatewayError,
    ProviderGatewayService,
    ProviderOperation,
    ProviderRegistry,
    ProviderRejectedError,
    ProviderRequest,
    ProviderResponse,
    ProviderResponseStatus,
    ProviderTransportError,
    ProviderTransportResponse,
    ProviderUnavailableError,
    UnsupportedJurisdictionError,
    UnsupportedProviderError,
)
from .synthetic_transport import SyntheticProviderTransport, SyntheticTransportObservation

__all__ = [
    "AuthorizationRequest",
    "AuthorizationResult",
    "AuthorizationStatus",
    "ConfiguredProviderAdapter",
    "CscUnavailableError",
    "FakeFiscalGateway",
    "FakeGatewayMode",
    "FiscalGateway",
    "FiscalGatewayClient",
    "FiscalProviderTransport",
    "GatewayContractError",
    "GatewayProviderMetadata",
    "MalformedProviderResponseError",
    "ProviderAuthenticationError",
    "ProviderCredentialsUnavailableError",
    "ProviderDescriptor",
    "ProviderGatewayError",
    "ProviderGatewayService",
    "ProviderOperation",
    "ProviderRegistry",
    "ProviderRejectedError",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderResponseStatus",
    "ProviderTransportError",
    "ProviderTransportResponse",
    "ProviderUnavailableError",
    "SyntheticProviderTransport",
    "SyntheticTransportObservation",
    "UnsupportedJurisdictionError",
    "UnsupportedProviderError",
]
