"""Public provider-neutral Vault/KMS boundary for FM Fiscal V2."""

from .contracts import (
    EphemeralCertificateMaterial,
    EphemeralCscMaterial,
    EphemeralProviderCredentialsMaterial,
    EphemeralSecretMaterial,
    FiscalSecretVault,
    SecretAuthorizationError,
    SecretMaterialTypeError,
    SecretResolutionContext,
    SecretResolutionError,
    SecretResolutionService,
    SecretUnavailableError,
    SecretUsagePurpose,
)
from .external import (
    ExternalFiscalSecretVault,
    ExternalSecretBackendError,
    ExternalSecretBackendUnavailable,
    ExternalSecretClient,
    ExternalSecretPermissionDenied,
    ExternalSecretRecord,
    NullSecretAccessAuditSink,
    SecretAccessAuditEvent,
    SecretAccessAuditSink,
    SystemExternalSecretClock,
)
from .in_memory import InMemorySyntheticFiscalSecretVault

__all__ = [
    "EphemeralCertificateMaterial",
    "EphemeralCscMaterial",
    "EphemeralProviderCredentialsMaterial",
    "EphemeralSecretMaterial",
    "ExternalFiscalSecretVault",
    "ExternalSecretBackendError",
    "ExternalSecretBackendUnavailable",
    "ExternalSecretClient",
    "ExternalSecretPermissionDenied",
    "ExternalSecretRecord",
    "FiscalSecretVault",
    "InMemorySyntheticFiscalSecretVault",
    "NullSecretAccessAuditSink",
    "SecretAccessAuditEvent",
    "SecretAccessAuditSink",
    "SecretAuthorizationError",
    "SecretMaterialTypeError",
    "SecretResolutionContext",
    "SecretResolutionError",
    "SecretResolutionService",
    "SecretUnavailableError",
    "SecretUsagePurpose",
    "SystemExternalSecretClock",
]
